<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-L6NUOVH" name="com.example.testframework.testng.TimeOutTest" tests="1" failures="1" timestamp="4 Aug 2017 14:24:36 GMT" time="0.022" errors="0">
  <testcase name="testBook" time="0.022" classname="com.example.testframework.testng.TimeOutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testBook() didn&#039;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testBook() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- testBook -->
</testsuite> <!-- com.example.testframework.testng.TimeOutTest -->
